type Frontmatter {
  title: String
  subtitle: String
  description: String
  date: Date @dateformat
  notice: [String!]
  tags: [String!]
  places: [String!]
  people: [String!]
}

type Metadata {
  date: Date! @dateformat
  category: String!
  slug: String!
  title: String!
  subtitle: String
  notice: [String!]!
  tags: [String!]!
  places: [String!]!
  people: [String!]!
  description: String
}

type Post implements Node {
  id: ID!
  metadata: Metadata!
}

type PostMdx implements Node {
  id: ID!
  post: Post!
  mdx: Mdx!
}

type PostPoem implements Node {
  id: ID!
  post: Post!
  poem: Poem!
}
