# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Molossus Spondee
email: molossusspondee@gmail.com
description: >-
  mostly poetry right now
baseurl: ""
url: "https://mstewartgallus.github.io"

theme: minima
plugins:
  - jekyll-feed

twitter_username: MSpondee
github_username: mstewartgallus

minima:
  social_links:
    twitter: MSpondee
    github: mstewartgallus
    stackoverflow: "Molossus Spondee"
    linkedin: mstewartgallus

defaults:
  -
    scope:
      path: ""
    values:
      author: "Molly Stewart-Gallus"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "_posts/poem"
      type: "posts"
    values:
      layout: "poem"
      categories: "poetry"
  -
    scope:
      path: "_posts/prose"
      type: "posts"
    values:
      layout: "prose"
      categories: "prose"