title: Words to Kick Your Teeth Out
email: molossusspondee@gmail.com
author:
  name: "Molossus Spondee"
  url: "/about"
description: >-
  lol, lmao
baseurl: ""
url: "https://mstewartgallus.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

rss: "Feed"
social:
  name: "Molossus Spondee"
  links:
    - https://twitter.com/MSpondee
    - https://www.linkedin.com/in/mstewartgallus
    - https://github.com/mstewartgallus
twitter:
  username: MSpondee
  card: summary
github: mstewartgallus
linkedin: mstewartgallus
stackoverflow: "Molossus Spondee"

defaults:
  -
    scope:
      path: ""
    values:
      author:
        name: "Molossus Spondee"
        twitter: MSpondee
        url: "/about"
      layout: "default"
  -
    scope:
      path: "assets"
      type: "pages"
    values:
      layout: "none"
  -
    scope:
      path: "_posts/poem"
      type: "posts"
    values:
      layout: "poem"
      categories: "poem"
  -
    scope:
      path: "_posts/prose"
      type: "posts"
    values:
      layout: "prose"
      categories: "prose"