title: Words to Kick Your Teeth Out
author: mspondee
description: >-
  lol, lmao
baseurl: ""
url: "https://mstewartgallus.github.io"
lang: "en-CA"

plugins:
  - jekyll-sitemap

source: src

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      author: "mspondee"
  -
    scope:
      path: "assets"
    values:
      layout: "none"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      permalink: /:categories/:year/:month/:day/:title/
  -
    scope:
      path: "_posts/web"
      type: "posts"
    values:
      layout: "post"
      categories: "Web"
  -
    scope:
      path: "_posts/poem"
      type: "posts"
    values:
      layout: "poem"
      categories: "Poem"
  -
    scope:
      path: "_posts/prose"
      type: "posts"
    values:
      layout: "prose"
      categories: "Prose"
 