type Frontmatter {
  title: String
  subtitle: String
  description: String
  date: Date @dateformat
  notice: [String!]
  tags: [String!]
  places: [String!]
  people: [String!]
}

type PostMdx implements Node & Post @childOf(types: ["Mdx"]) {
  id: ID!
  metadata: Metadata!
  mdx: Mdx!
}
