type Index implements Node @dontInfer {
  id: ID!
  label: String!
  links: [Link!]! @link(by: "index.id", from: "id")
}

type Link implements Node @dontInfer @childOf(types: ["Post"]) {
  id: ID!
  index: Index! @link
  post: Post! @link
  date: Date! @dateformat
  next: Link
  previous: Link
}
