type Index implements Node @dontInfer {
  id: ID!
  label: String!
}

type Link implements Node @dontInfer @childOf(types: ["Post"]) {
  id: ID!
  index: Index!
  post: Post!
  next: Link
  previous: Link
  date: Date! @dateformat
}
