type Post implements Node @dontInfer {
  name: String!
  date: Date! @dateformat
  category: String!
  slug: String!
  author: AuthorYaml @link(by: "name")

  title: String!
  subtitle: String
  notice: [String!]!
  tags: [String!]!
  places: [String!]!
  people: [String!]!
  description: String
}

type Link implements Node @dontInfer @childOf(types: ["Post"]) {
  id: ID!
  index: Index! @link
  post: Post! @link(from: "parent")
  next: Link
  previous: Link
}

type Index implements Node @dontInfer {
  id: ID!
}
