type Metadata @dontInfer {
  name: String!
  date: Date! @dateformat
  category: String!
  slug: String!

  title: String!
  subtitle: String
  notice: [String!]!
  tags: [String!]!
  places: [String!]!
  people: [String!]!
  description: String
}

interface Post implements Node {
  id: ID!
  metadata: Metadata!
}

type Content @dontInfer {
  index: Index! @link
  post: Post! @link
  date: Date! @dateformat
  next: Link
  previous: Link
}

interface Link implements Node {
  id: ID!
  content: Content!
}

interface Index implements Node {
  id: ID!
}
