type Comments {
  host: String!
  id: String!
}

type Post implements Node @dontInfer {
  name: String!
  date: Date! @dateformat
  category: String!
  slug: String!
  author: AuthorYaml @link(by: "name")

  title: String!
  subtitle: String
  notice: [String!]!
  tags: [String!]!
  places: [String!]!
  people: [String!]!
  description: String

  comments: Comments
}